steps:

#- id: 'Gerando my-project-17-01-1983-a4fd1c6b41ee.json'
#  name: 'gcr.io/cloud-builders/gcloud'
#  args:
#    - kms
#    - decrypt
#    - --ciphertext-file=./storage/credentials/google/my-project-17-01-1983-a4fd1c6b41ee.json.enc
#    - --plaintext-file=./storage/credentials/google/my-project-17-01-1983-a4fd1c6b41ee.json
#    - --location=global
#    - --keyring=testing-lesson-d
#    - --key=service-account-d
#    - --project=$PROJECT_ID

- id: 'Rodando-docker-compose'
  name: 'docker/compose'
  args: ['-f','docker-compose.prod.yaml','up','-d']
  env:
      - GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID
      - GOOGLE_CLOUD_KEY_FILE=my-project-17-01-1983-a4fd1c6b41ee.json
      - GOOGLE_CLOUD_STORAGE_BUCKET=code-micro-videos-d
      - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.googleapis.com/code-micro-videos-d
      - TESTING_PROD=true

- id: 'Chown in /var/www'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www']

- id: 'Rodando composer'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','composer','install']

#- id: 'Rodando cache:clear'
#  name: 'gcr.io/cloud-builders/docker'
#  args: ['exec','-t','app','php','/var/www/artisan','cache:clear']

#- id: 'Rodando config:clear'
#  name: 'gcr.io/cloud-builders/docker'
#  args: ['exec','-t','app','php','/var/www/artisan','config:clear'] 

- id: 'Copiando .env'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','cp','.env.example','.env']

- id: 'Copiando .env.testing'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','cp','.env.testing.example','.env.testing']

- id: 'Copiando .env.testing'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','cat','.env.testing']

- id: 'Rodando key:generate'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/artisan','key:generate']

- id: 'Rodando migrations'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/artisan','migrate']

- id: 'Rodando PHPUnit'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/vendor/bin/phpunit','-c','/var/www/phpunit.xml']
